### ISSUE TITLE
Titulos y subtitulos en blanco no se ven en páginas moviles.

### ISSUE THREAD

**Issue by blur50** [lpagency/tika#8]
En una vista móvil, las paginas que tiene un titulo o subtitulo, no se logra ver el texto por el color blanco de la letra y el fondo.
![image](https://user-images.githubusercontent.com/21262557/40794834-584a342a-64ce-11e8-80a2-e76fa7550d0b.png)
![image](https://user-images.githubusercontent.com/21262557/40794781-2e1b1106-64ce-11e8-885a-9e12a50a8d4b.png)

**Comment by WayoCarrasco** [comment]
resuelto en https://trello.com/c/e7p2ERUD/248-qa-banner-tika
